import { test, expect, type Page } from '@playwright/test';
import { pathToFileURL } from 'node:url';
import { existsSync } from 'node:fs';
import path from 'node:path';

// The dashboard is generated by scripts/sync-ledger.py and shipped as one
// self-contained HTML file. Until now nothing verified that it actually renders
// or that its filters work, so a broken template would have shipped silently.
const DASHBOARD = path.resolve(
  __dirname,
  '.fixture/.project/.engineering/dashboards/project-dashboard.html',
);

test.beforeAll(() => {
  if (!existsSync(DASHBOARD)) {
    throw new Error(
      `Fixture missing at ${DASHBOARD}. Run \`npm run fixture\` first ` +
        '(python -B ../../scripts/build-dashboard-fixture.py --out .fixture).',
    );
  }
});

const open = async (page: Page) => page.goto(pathToFileURL(DASHBOARD).href);

const visibleRows = (page: Page) =>
  page.locator('#artifacts tbody tr').filter({ visible: true });

test.describe('project dashboard', () => {
  test('renders the summary, panels and artifact table', async ({ page }) => {
    await open(page);

    await expect(page.getByRole('heading', { name: 'Engineering Lifecycle Dashboard' })).toBeVisible();

    for (const panel of [
      'Risks',
      'Open action items',
      'Open human tasks',
      'Open questions',
      'Council runs',
      'Recent artifacts',
    ]) {
      await expect(page.getByRole('heading', { name: panel })).toBeVisible();
    }

    // Content, not just chrome: the fixture's data must actually reach the page.
    await expect(page.getByText('Which region hosts the export bucket?')).toBeVisible();
    await expect(page.getByText('Confirm the production rollout window')).toBeVisible();
    await expect(page.getByText('Add a retention policy to the export bucket')).toBeVisible();

    // An answered question is not an open one.
    await expect(page.getByText('How long is a session token valid?')).toHaveCount(0);

    await expect(visibleRows(page).first()).toBeVisible();
  });

  test('search narrows the artifact table', async ({ page }) => {
    await open(page);
    const before = await visibleRows(page).count();
    expect(before).toBeGreaterThan(1);

    await page.locator('#search').fill('push-notifications');
    const after = await visibleRows(page).count();

    expect(after).toBeGreaterThan(0);
    expect(after).toBeLessThan(before);
    for (const row of await visibleRows(page).all()) {
      expect(await row.getAttribute('data-path')).toContain('push-notifications');
    }

    await page.locator('#search').fill('');
    expect(await visibleRows(page).count()).toBe(before);
  });

  test('status chips filter, and toggle off again', async ({ page }) => {
    await open(page);
    const before = await visibleRows(page).count();

    const chip = page.locator('.filter[data-dim="status"]').first();
    const value = await chip.getAttribute('data-val');
    await chip.click();

    const filtered = await visibleRows(page).count();
    expect(filtered).toBeGreaterThan(0);
    expect(filtered).toBeLessThanOrEqual(before);
    for (const row of await visibleRows(page).all()) {
      expect(await row.getAttribute('data-status')).toBe(value);
    }

    // Clicking the active chip again clears the filter rather than doing nothing.
    await chip.click();
    expect(await visibleRows(page).count()).toBe(before);
  });

  test('clicking a column header sorts, and clicking again reverses', async ({ page }) => {
    await open(page);
    const paths = () => visibleRows(page).evaluateAll((rows) => rows.map((r) => r.getAttribute('data-path') ?? ''));

    const header = page.locator('#artifacts thead th').first();
    await header.click();
    const ascending = await paths();

    await header.click();
    const descending = await paths();

    expect(descending).toEqual([...ascending].reverse());
    expect(ascending).not.toEqual(descending);
  });

  test('is self-contained: no external requests', async ({ page }) => {
    // A dashboard that fetches a font or a script is useless offline, and it is
    // meant to be openable straight from disk.
    const external: string[] = [];
    page.on('request', (request) => {
      if (!request.url().startsWith('file://')) external.push(request.url());
    });
    await open(page);
    expect(external).toEqual([]);
  });
});
